# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 01:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('answer_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('latest_question_published', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('rank', models.IntegerField(default=0)),
                ('answer_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('question_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('question_isComplete', models.BooleanField(default=False)),
                ('latest_question_published', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostBar.Category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('popular', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostBar.Question'),
        ),
    ]
