# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_content',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='rank_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
