# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0002_auto_20190228_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='rank_number',
            new_name='rank_count',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='rank',
            new_name='rank_points',
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
