# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0003_auto_20190228_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_name',
            new_name='name',
        ),
    ]
