# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostBar', '0009_question_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='liked_users',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
