# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostBar', '0011_auto_20190307_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ranked_users',
            field=models.ManyToManyField(related_name='ranked_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
