# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0013_auto_20190307_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
