# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0014_auto_20190312_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
    ]
