# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostBar', '0016_answer_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rank_points',
        ),
    ]
